set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

# Кросс-библиотека Qt6 из MSYS2
set(QT6_MINGW_DIR "$ENV{HOME}/mingw-qt6/mingw64")

list(APPEND CMAKE_PREFIX_PATH "${QT6_MINGW_DIR}")
list(APPEND CMAKE_FIND_ROOT_PATH "${QT6_MINGW_DIR}" "/usr/x86_64-w64-mingw32")

# СТРОГИЙ РЕЖИМ: искать ВСЁ только внутри CMAKE_FIND_ROOT_PATH
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)